export interface Idiom {
  id: string
  idiom: string
  meaning: string
  example: string
  category: string
  level: string
}

export const IDIOMS: Idiom[] = [
  { id: '1', idiom: 'Break the ice', meaning: 'Начать разговор, снять напряжение', example: 'He told a joke to break the ice at the meeting.', category: 'Общение', level: 'B1' },
  { id: '2', idiom: 'Hit the nail on the head', meaning: 'Попасть в точку', example: 'You hit the nail on the head with that analysis.', category: 'Общение', level: 'B1' },
  { id: '3', idiom: 'Bite the bullet', meaning: 'Стиснуть зубы и сделать что-то неприятное', example: 'I bit the bullet and went to the dentist.', category: 'Решения', level: 'B1' },
  { id: '4', idiom: 'Under the weather', meaning: 'Чувствовать себя плохо', example: "I'm feeling a bit under the weather today.", category: 'Здоровье', level: 'A2' },
  { id: '5', idiom: 'Once in a blue moon', meaning: 'Очень редко', example: 'We only visit them once in a blue moon.', category: 'Время', level: 'A2' },
  { id: '6', idiom: 'Spill the beans', meaning: 'Разболтать секрет', example: "Don't spill the beans about the surprise party.", category: 'Общение', level: 'B1' },
  { id: '7', idiom: 'Hit the sack', meaning: 'Идти спать', example: "I'm exhausted — time to hit the sack.", category: 'Быт', level: 'A2' },
  { id: '8', idiom: 'Cost an arm and a leg', meaning: 'Стоить очень дорого', example: 'That new phone costs an arm and a leg.', category: 'Деньги', level: 'A2' },
  { id: '9', idiom: 'Beat around the bush', meaning: 'Ходить вокруг да около', example: 'Stop beating around the bush and tell me the truth.', category: 'Общение', level: 'B1' },
  { id: '10', idiom: 'A blessing in disguise', meaning: 'Что-то плохое, оказавшееся хорошим', example: 'Losing that job was a blessing in disguise.', category: 'Жизнь', level: 'B2' },
  { id: '11', idiom: 'Get out of hand', meaning: 'Выйти из-под контроля', example: 'The situation got out of hand quickly.', category: 'Ситуации', level: 'B1' },
  { id: '12', idiom: 'On the fence', meaning: 'Не определиться с решением', example: "I'm still on the fence about which job to take.", category: 'Решения', level: 'B1' },
  { id: '13', idiom: "Let the cat out of the bag", meaning: 'Случайно раскрыть секрет', example: 'She let the cat out of the bag about the wedding.', category: 'Общение', level: 'B1' },
  { id: '14', idiom: 'Bite off more than you can chew', meaning: 'Взять на себя слишком много', example: 'He bit off more than he could chew with three projects.', category: 'Работа', level: 'B2' },
  { id: '15', idiom: 'Kill two birds with one stone', meaning: 'Убить двух зайцев одним выстрелом', example: 'Taking the scenic route kills two birds with one stone.', category: 'Эффективность', level: 'B1' },
  { id: '16', idiom: 'The ball is in your court', meaning: 'Теперь решение за тобой', example: "I've made my offer — the ball is in your court now.", category: 'Решения', level: 'B2' },
  { id: '17', idiom: 'Burn bridges', meaning: 'Сжечь мосты', example: "Don't burn bridges when leaving a job.", category: 'Отношения', level: 'B2' },
  { id: '18', idiom: 'Cutting corners', meaning: 'Делать кое-как, срезать углы', example: 'They cut corners and now the building has problems.', category: 'Работа', level: 'B1' },
  { id: '19', idiom: 'Hit the ground running', meaning: 'Начать энергично, с места в карьер', example: 'She hit the ground running in her new role.', category: 'Работа', level: 'B2' },
  { id: '20', idiom: 'Jump on the bandwagon', meaning: 'Присоединиться к модному течению', example: 'Everyone jumped on the social media bandwagon.', category: 'Тренды', level: 'B2' },
  { id: '21', idiom: 'Miss the boat', meaning: 'Упустить возможность', example: 'He missed the boat on that investment opportunity.', category: 'Возможности', level: 'B1' },
  { id: '22', idiom: 'Sit on the fence', meaning: 'Занимать нейтральную позицию', example: 'Politicians often sit on the fence to avoid controversy.', category: 'Политика', level: 'B2' },
  { id: '23', idiom: "Steal someone's thunder", meaning: 'Перехватить чей-то успех', example: 'She stole his thunder by announcing it first.', category: 'Отношения', level: 'C1' },
  { id: '24', idiom: 'Turn a blind eye', meaning: 'Закрывать глаза на что-то', example: 'The manager turned a blind eye to their lateness.', category: 'Работа', level: 'B2' },
  { id: '25', idiom: 'Under the radar', meaning: 'Незамеченный, тайный', example: 'The startup stayed under the radar for two years.', category: 'Бизнес', level: 'B2' },
  { id: '26', idiom: 'Wrap your head around', meaning: 'Понять что-то сложное', example: "I can't wrap my head around quantum physics.", category: 'Обучение', level: 'B1' },
  { id: '27', idiom: 'Go the extra mile', meaning: 'Сделать больше чем нужно', example: 'She always goes the extra mile for her clients.', category: 'Работа', level: 'B1' },
  { id: '28', idiom: 'In hot water', meaning: 'В горячей воде / в беде', example: 'He got in hot water for missing the deadline.', category: 'Проблемы', level: 'B1' },
  { id: '29', idiom: 'Read between the lines', meaning: 'Читать между строк', example: "Reading between the lines, she wasn't happy.", category: 'Общение', level: 'B2' },
  { id: '30', idiom: "Pull someone's leg", meaning: 'Разыгрывать кого-то', example: 'Are you serious or just pulling my leg?', category: 'Юмор', level: 'A2' },
  { id: '31', idiom: 'Barking up the wrong tree', meaning: 'Искать не там, ошибаться', example: "You're barking up the wrong tree if you think I took it.", category: 'Ошибки', level: 'B1' },
  { id: '32', idiom: 'Bite the hand that feeds you', meaning: 'Кусать руку которая кормит', example: "Don't bite the hand that feeds you.", category: 'Отношения', level: 'B2' },
  { id: '33', idiom: 'Break a leg', meaning: 'Ни пуха ни пера! (пожелание удачи)', example: "Break a leg at your audition tonight!", category: 'Общение', level: 'A2' },
  { id: '34', idiom: 'Burn the midnight oil', meaning: 'Работать допоздна', example: "She burned the midnight oil to finish the report.", category: 'Работа', level: 'B1' },
  { id: '35', idiom: 'Caught red-handed', meaning: 'Поймать с поличным', example: "He was caught red-handed stealing.", category: 'Ситуации', level: 'B1' },
  { id: '36', idiom: 'Cry over spilt milk', meaning: 'Жалеть о прошлом', example: "No use crying over spilt milk.", category: 'Мудрость', level: 'A2' },
  { id: '37', idiom: 'Every cloud has a silver lining', meaning: 'Нет худа без добра', example: "Every cloud has a silver lining.", category: 'Оптимизм', level: 'B1' },
  { id: '38', idiom: 'Face the music', meaning: 'Принять последствия', example: "It's time to face the music.", category: 'Ответственность', level: 'B1' },
  { id: '39', idiom: 'Get cold feet', meaning: 'Струсить в последний момент', example: "She got cold feet and didn't give the speech.", category: 'Эмоции', level: 'B1' },
  { id: '40', idiom: 'Get the ball rolling', meaning: 'Начать дело', example: "Let's get the ball rolling on this project.", category: 'Работа', level: 'B1' },
  { id: '41', idiom: 'Give the benefit of the doubt', meaning: 'Дать кредит доверия', example: "I'll give him the benefit of the doubt.", category: 'Отношения', level: 'B2' },
  { id: '42', idiom: 'Go back to the drawing board', meaning: 'Начать всё заново', example: "The plan failed — go back to the drawing board.", category: 'Работа', level: 'B1' },
  { id: '43', idiom: 'Hang in there', meaning: 'Держись! Не сдавайся!', example: "Hang in there — things will get better.", category: 'Поддержка', level: 'A2' },
  { id: '44', idiom: 'Hit the books', meaning: 'Засесть за учёбу', example: "I need to hit the books before the exam.", category: 'Учёба', level: 'A2' },
  { id: '45', idiom: 'It takes two to tango', meaning: 'В ссоре виноваты оба', example: "It takes two to tango.", category: 'Отношения', level: 'B2' },
  { id: '46', idiom: 'Keep your chin up', meaning: 'Не вешай нос', example: "Keep your chin up — you'll find another job.", category: 'Поддержка', level: 'A2' },
  { id: '47', idiom: 'Kick the bucket', meaning: 'Умереть (разг.)', example: "He finally kicked the bucket at 95.", category: 'Юмор', level: 'B1' },
  { id: '48', idiom: 'Know the ropes', meaning: 'Знать всё как свои пять пальцев', example: "Ask Sarah — she knows the ropes.", category: 'Опыт', level: 'B1' },
  { id: '49', idiom: 'Leave no stone unturned', meaning: 'Сделать всё возможное', example: "We'll leave no stone unturned.", category: 'Усилия', level: 'B2' },
  { id: '50', idiom: 'Let sleeping dogs lie', meaning: 'Не буди лихо пока тихо', example: "Let sleeping dogs lie.", category: 'Мудрость', level: 'B1' },
  { id: '51', idiom: 'Make a long story short', meaning: 'Короче говоря', example: "To make a long story short, we missed the train.", category: 'Общение', level: 'A2' },
  { id: '52', idiom: 'Make ends meet', meaning: 'Сводить концы с концами', example: "It's hard to make ends meet.", category: 'Деньги', level: 'B1' },
  { id: '53', idiom: 'No pain, no gain', meaning: 'Без труда не вытащишь рыбку', example: "Train harder — no pain, no gain!", category: 'Мотивация', level: 'A2' },
  { id: '54', idiom: 'Not rocket science', meaning: 'Не так уж сложно', example: "It's not rocket science — just follow instructions.", category: 'Простота', level: 'A2' },
  { id: '55', idiom: 'Off the top of my head', meaning: 'Навскидку', example: "Off the top of my head, I'd say fifty people.", category: 'Общение', level: 'B1' },
  { id: '56', idiom: 'On the ball', meaning: 'Быть начеку', example: "You need to be on the ball during the presentation.", category: 'Работа', level: 'B1' },
  { id: '57', idiom: 'On the tip of my tongue', meaning: 'На кончике языка', example: "His name is on the tip of my tongue!", category: 'Память', level: 'A2' },
  { id: '58', idiom: 'Out of the blue', meaning: 'Вдруг, ни с того ни с сего', example: "Out of the blue, she called me.", category: 'Неожиданность', level: 'B1' },
  { id: '59', idiom: 'Over the moon', meaning: 'На седьмом небе от счастья', example: "She was over the moon about the promotion.", category: 'Эмоции', level: 'B1' },
  { id: '60', idiom: 'Pass the buck', meaning: 'Перекладывать ответственность', example: "Stop passing the buck.", category: 'Ответственность', level: 'B2' },
  { id: '61', idiom: 'Piece of cake', meaning: 'Проще простого', example: "The exam was a piece of cake!", category: 'Простота', level: 'A2' },
  { id: '62', idiom: 'Play it by ear', meaning: 'Действовать по ситуации', example: "Let's play it by ear.", category: 'Планирование', level: 'B1' },
  { id: '63', idiom: 'Pull strings', meaning: 'Использовать связи', example: "He pulled strings to get the job.", category: 'Связи', level: 'B2' },
  { id: '64', idiom: 'Put your foot in your mouth', meaning: 'Попасть впросак', example: "I really put my foot in my mouth.", category: 'Ошибки', level: 'B1' },
  { id: '65', idiom: 'Raise the bar', meaning: 'Поднять планку', example: "This project has raised the bar.", category: 'Стандарты', level: 'B2' },
  { id: '66', idiom: 'Ring a bell', meaning: 'Что-то напоминать', example: "Does that name ring a bell?", category: 'Память', level: 'B1' },
  { id: '67', idiom: 'Rock the boat', meaning: 'Раскачивать лодку', example: "Don't rock the boat — things are going well.", category: 'Стабильность', level: 'B2' },
  { id: '68', idiom: 'Saved by the bell', meaning: 'Спастись в последний момент', example: "I was saved by the bell.", category: 'Удача', level: 'B1' },
  { id: '69', idiom: 'See eye to eye', meaning: 'Сходиться во мнениях', example: "We don't always see eye to eye.", category: 'Отношения', level: 'B1' },
  { id: '70', idiom: 'Shoot the breeze', meaning: 'Болтать ни о чём', example: "We spent the afternoon shooting the breeze.", category: 'Общение', level: 'B1' },
  { id: '71', idiom: 'Skeleton in the closet', meaning: 'Скелет в шкафу', example: "Every family has a skeleton in the closet.", category: 'Секреты', level: 'B2' },
  { id: '72', idiom: 'Speak of the devil', meaning: 'Лёгок на помине', example: "Speak of the devil — we were just talking about you!", category: 'Общение', level: 'A2' },
  { id: '73', idiom: 'Stab someone in the back', meaning: 'Предать', example: "He stabbed me in the back.", category: 'Предательство', level: 'B2' },
  { id: '74', idiom: 'Step up your game', meaning: 'Подтянуться', example: "You need to step up your game.", category: 'Мотивация', level: 'B1' },
  { id: '75', idiom: 'Take it with a grain of salt', meaning: 'Воспринимать скептически', example: "Take his advice with a grain of salt.", category: 'Скептицизм', level: 'B2' },
  { id: '76', idiom: 'The last straw', meaning: 'Последняя капля', example: "That was the last straw.", category: 'Эмоции', level: 'B1' },
  { id: '77', idiom: 'The tip of the iceberg', meaning: 'Верхушка айсберга', example: "This is just the tip of the iceberg.", category: 'Ситуации', level: 'B1' },
  { id: '78', idiom: 'Throw in the towel', meaning: 'Сдаться', example: "After three attempts, he threw in the towel.", category: 'Сдача', level: 'B1' },
  { id: '79', idiom: 'Tie the knot', meaning: 'Пожениться', example: "They finally tied the knot.", category: 'Отношения', level: 'A2' },
  { id: '80', idiom: 'Time flies', meaning: 'Время летит', example: "Time flies when you're having fun!", category: 'Время', level: 'A1' },
  { id: '81', idiom: 'Up in the air', meaning: 'Под вопросом', example: "The deal is still up in the air.", category: 'Неопределённость', level: 'B1' },
  { id: '82', idiom: 'Vanish into thin air', meaning: 'Исчезнуть без следа', example: "My keys have vanished into thin air!", category: 'Исчезновение', level: 'B1' },
  { id: '83', idiom: 'Wear your heart on your sleeve', meaning: 'Быть открытым, не скрывать чувств', example: "She wears her heart on her sleeve.", category: 'Характер', level: 'B2' },
  { id: '84', idiom: 'When pigs fly', meaning: 'Когда рак на горе свистнет', example: "He'll apologise when pigs fly.", category: 'Юмор', level: 'B1' },
  { id: '85', idiom: 'With flying colours', meaning: 'С блеском, на отлично', example: "She passed with flying colours.", category: 'Успех', level: 'B1' },
  { id: '86', idiom: 'Actions speak louder than words', meaning: 'Поступки говорят громче слов', example: "Actions speak louder than words.", category: 'Мудрость', level: 'B1' },
  { id: '87', idiom: 'Add fuel to the fire', meaning: 'Подливать масло в огонь', example: "His comment added fuel to the fire.", category: 'Конфликт', level: 'B2' },
  { id: '88', idiom: 'At the drop of a hat', meaning: 'Сразу же, незамедлительно', example: "She would travel anywhere at the drop of a hat.", category: 'Готовность', level: 'B2' },
  { id: '89', idiom: 'Back to square one', meaning: 'Вернуться к началу', example: "The project failed — back to square one.", category: 'Начало', level: 'B1' },
  { id: '90', idiom: 'Bite off more than you can chew', meaning: 'Взять на себя слишком много', example: "He bit off more than he could chew.", category: 'Ошибки', level: 'B2' },
  { id: '91', idiom: 'Blow hot and cold', meaning: 'Быть непостоянным', example: "He keeps blowing hot and cold.", category: 'Характер', level: 'B2' },
  { id: '92', idiom: 'Get a taste of your own medicine', meaning: 'Получить по заслугам', example: "He got a taste of his own medicine.", category: 'Справедливость', level: 'B2' },
  { id: '93', idiom: 'Go viral', meaning: 'Стать вирусным', example: "Her video went viral overnight.", category: 'Современное', level: 'B1' },
  { id: '94', idiom: 'Hit the ground running', meaning: 'Начать энергично', example: "She hit the ground running in her new role.", category: 'Работа', level: 'B2' },
  { id: '95', idiom: 'Jump on the bandwagon', meaning: 'Присоединиться к модному течению', example: "Everyone jumped on the social media bandwagon.", category: 'Тренды', level: 'B2' },
  { id: '96', idiom: 'Miss the boat', meaning: 'Упустить возможность', example: "He missed the boat on that investment.", category: 'Возможности', level: 'B1' },
  { id: '97', idiom: 'Turn a blind eye', meaning: 'Закрывать глаза', example: "The manager turned a blind eye to their lateness.", category: 'Работа', level: 'B2' },
  { id: '98', idiom: 'Under the radar', meaning: 'Незамеченный', example: "The startup stayed under the radar.", category: 'Бизнес', level: 'B2' },
  { id: '99', idiom: 'Wrap your head around', meaning: 'Понять что-то сложное', example: "I can't wrap my head around quantum physics.", category: 'Обучение', level: 'B1' },
  { id: '100', idiom: "You can't have your cake and eat it", meaning: 'Нельзя иметь всё сразу', example: "You can't have your cake and eat it — choose.", category: 'Мудрость', level: 'B2' },
]

export const IDIOM_CATEGORIES = [...new Set(IDIOMS.map(i => i.category))].sort()
