export interface PhrasalVerb {
  id: string
  verb: string
  translation: string
  examples: string[]
  category: string
}

export interface PhrasalVerbCategory {
  id: string
  title: string
  description: string
  verbs: PhrasalVerb[]
}

export const PHRASAL_VERBS_DATA: PhrasalVerbCategory[] = [
  {
    id: 'daily',
    title: 'Быт и повседневные дела',
    description: 'Домашняя рутина, уход за одеждой и повседневные задачи',
    verbs: [
      { id: 'turn-on', verb: 'Turn on', translation: 'включать', examples: ['Tom turned on the lights.', 'Can you turn on the TV?'], category: 'daily' },
      { id: 'turn-off', verb: 'Turn off', translation: 'выключать', examples: ['Please turn off the TV.', 'Turn off the lights when you leave.'], category: 'daily' },
      { id: 'put-on', verb: 'Put on', translation: 'надевать', examples: ["Put on your jacket, it's cold.", 'She put on her coat and left.'], category: 'daily' },
      { id: 'take-off-clothes', verb: 'Take off (clothes)', translation: 'снимать одежду', examples: ['Take off your shoes please.', 'I took off my jacket.'], category: 'daily' },
      { id: 'clean-up', verb: 'Clean up', translation: 'убираться, приводить в порядок', examples: ['Did you clean up your room?', 'We need to clean up the kitchen.'], category: 'daily' },
      { id: 'throw-away', verb: 'Throw away', translation: 'выбрасывать', examples: ["Don't throw away your old clothes.", 'I threw away the broken lamp.'], category: 'daily' },
      { id: 'put-away', verb: 'Put away', translation: 'убирать на место', examples: ['Put away your toys.', 'She put away the dishes after dinner.'], category: 'daily' },
      { id: 'wash-up', verb: 'Wash up', translation: 'мыть посуду', examples: ["I'll wash up after dinner.", 'Can you wash up while I cook?'], category: 'daily' },
      { id: 'warm-up', verb: 'Warm up', translation: 'разогревать еду', examples: ["I'll warm up the soup.", 'Warm up the leftovers in the microwave.'], category: 'daily' },
      { id: 'mop-up', verb: 'Mop up', translation: 'вытирать разлитое', examples: ['I need to mop up the spill in the kitchen.', 'He mopped up the water on the floor.'], category: 'daily' },
      { id: 'zip-up', verb: 'Zip up', translation: 'застегивать молнию', examples: ['Zip up your jacket.', 'She zipped up her bag.'], category: 'daily' },
      { id: 'use-up', verb: 'Use up', translation: 'израсходовать полностью', examples: ['We used up all the paper.', "I've used up all my savings."], category: 'daily' },
      { id: 'dry-up', verb: 'Dry up', translation: 'засыхать, высыхать', examples: ['The paint dried up quickly.', 'The river dried up in summer.'], category: 'daily' },
      { id: 'blow-out', verb: 'Blow out', translation: 'задувать свечи', examples: ['Lisa blew out the candles on the cake.', 'Blow out the candles and make a wish.'], category: 'daily' },
      { id: 'pick-up', verb: 'Pick up', translation: 'забирать, поднимать', examples: ['Can you pick up the kids from school?', "I'll pick up some groceries after work.", 'I picked up the keys from the floor.'], category: 'daily' },
      { id: 'load-up', verb: 'Load up', translation: 'загружать', examples: ['We loaded up the car with groceries.', 'Load up the dishwasher, please.'], category: 'daily' },
    ],
  },
  {
    id: 'social',
    title: 'Общение и отношения',
    description: 'Социальное взаимодействие, воспитание и контакты между людьми',
    verbs: [
      { id: 'get-along', verb: 'Get along / Get on', translation: 'ладить, хорошо общаться', examples: ['We get along really well.', 'I get on really well with my co-workers.', "They don't get on at all."], category: 'social' },
      { id: 'look-after', verb: 'Look after', translation: 'присматривать, заботиться', examples: ['Jane looks after the children.', "I'll look after your cat while you are away."], category: 'social' },
      { id: 'bring-up', verb: 'Bring up', translation: 'воспитывать детей / упоминать тему', examples: ['They bring up three kids.', "Don't bring up politics during dinner.", 'You brought up a good point.'], category: 'social' },
      { id: 'hang-out', verb: 'Hang out', translation: 'проводить время, тусоваться', examples: ['We hang out in the park.', "Let's hang out this weekend."], category: 'social' },
      { id: 'come-over', verb: 'Come over', translation: 'заходить в гости', examples: ['Emma came over for dinner.', 'Come over whenever you want.'], category: 'social' },
      { id: 'drop-by', verb: 'Drop by', translation: 'заглянуть ненадолго', examples: ['Feel free to drop by anytime.', 'I dropped by her office yesterday.'], category: 'social' },
      { id: 'run-into', verb: 'Run into', translation: 'случайно встретить', examples: ['I ran into Mike today.', 'I ran into an old friend at the store.'], category: 'social' },
      { id: 'see-off', verb: 'See off', translation: 'провожать уезжающих', examples: ["I'll see you off at the airport.", 'The whole family came to see him off.'], category: 'social' },
      { id: 'get-together', verb: 'Get together', translation: 'собираться вместе', examples: ["Let's get together tomorrow.", 'The team gets together every Friday.'], category: 'social' },
      { id: 'make-up-reconcile', verb: 'Make up', translation: 'мириться', examples: ["Let's forget the past and make up.", 'They made up after the argument.'], category: 'social' },
      { id: 'let-down', verb: 'Let down', translation: 'подводить', examples: ["Don't let me down Jake.", 'I felt let down when he cancelled.'], category: 'social' },
      { id: 'look-up-to', verb: 'Look up to', translation: 'восхищаться, брать пример', examples: ['I look up to my older sister.', 'Children look up to their parents.'], category: 'social' },
      { id: 'take-after', verb: 'Take after', translation: 'быть похожим на родственника', examples: ['She takes after her mother.', 'He takes after his grandfather.'], category: 'social' },
      { id: 'show-off', verb: 'Show off', translation: 'хвастаться', examples: ['Jack showed off his new bike.', 'Stop showing off!'], category: 'social' },
      { id: 'point-out', verb: 'Point out', translation: 'указывать, замечать', examples: ['She pointed out my mistakes.', 'I want to point out a few issues.'], category: 'social' },
      { id: 'call-back', verb: 'Call back', translation: 'перезванивать', examples: ["I'll call you back.", 'He never called back.'], category: 'social' },
      { id: 'speak-up', verb: 'Speak up', translation: 'говорить громче', examples: ["Please speak up, I can't hear you.", "Don't be afraid to speak up."], category: 'social' },
    ],
  },
  {
    id: 'work',
    title: 'Работа и учёба',
    description: 'Профессиональная деятельность, анализ информации и обучение',
    verbs: [
      { id: 'find-out', verb: 'Find out', translation: 'выяснять, узнавать', examples: ['I need to find out the truth.', "Let's find out what happened."], category: 'work' },
      { id: 'figure-out', verb: 'Figure out', translation: 'сообразить, разобраться', examples: ["I can't figure out how to do this.", 'She figured out the answer quickly.'], category: 'work' },
      { id: 'work-out-solve', verb: 'Work out (solve)', translation: 'решать проблему', examples: ['We can work out this issue.', "I'm sure we'll work it out."], category: 'work' },
      { id: 'set-up', verb: 'Set up', translation: 'основывать бизнес / настраивать технику', examples: ['I want to set up my own business.', 'He set up the Wi-Fi in the new apartment.'], category: 'work' },
      { id: 'call-off', verb: 'Call off', translation: 'отменять', examples: ['Lisa called off the party.', 'They called off the meeting.'], category: 'work' },
      { id: 'put-off', verb: 'Put off', translation: 'откладывать', examples: ['Stop putting things off.', 'We put off the meeting until next week.'], category: 'work' },
      { id: 'fill-out', verb: 'Fill out', translation: 'заполнять форму/анкету', examples: ['Please fill out this application form.', 'Did you fill out the application?'], category: 'work' },
      { id: 'take-up', verb: 'Take up', translation: 'занимать должность / начинать хобби', examples: ["He'll take up his new position soon.", 'She took up yoga to improve her health.', 'I took up running to stay fit.'], category: 'work' },
      { id: 'turn-down', verb: 'Turn down', translation: 'отклонять, отказываться', examples: ['She turned down the job.', 'He turned down the invitation to the party.'], category: 'work' },
      { id: 'drop-out', verb: 'Drop out', translation: 'бросать учёбу', examples: ['George dropped out of college.', 'She dropped out of the course.'], category: 'work' },
      { id: 'go-through', verb: 'Go through', translation: 'изучать документы / проходить трудности', examples: ['I need to go through these documents.', 'I had to go through a lot of difficulties.'], category: 'work' },
      { id: 'work-on', verb: 'Work on', translation: 'работать над чем-либо', examples: ["I'm working on improving my English.", 'We need to work on this project.'], category: 'work' },
      { id: 'cut-back', verb: 'Cut back', translation: 'сокращать расходы', examples: ['We cut back on spending.', 'I need to cut back on sugar.'], category: 'work' },
      { id: 'pay-off', verb: 'Pay off', translation: 'окупаться, приносить результат', examples: ['All your hard work will pay off.', 'The investment finally paid off.'], category: 'work' },
      { id: 'look-up', verb: 'Look up', translation: 'искать информацию в словаре', examples: ['You can look up this word in the dictionary.', 'I looked it up online.'], category: 'work' },
      { id: 'write-down', verb: 'Write down', translation: 'записывать', examples: ['Write down my phone number.', 'Write down your ideas.'], category: 'work' },
      { id: 'speed-up', verb: 'Speed up', translation: 'ускорять', examples: ['Speed up your work.', 'Can we speed up the process?'], category: 'work' },
      { id: 'move-on', verb: 'Move on', translation: 'переходить к следующему', examples: ["Let's move on to the next topic.", "It's time to move on."], category: 'work' },
      { id: 'keep-on', verb: 'Keep on', translation: 'продолжать делать', examples: ['She keeps on calling me.', "Keep on practicing and you'll get better."], category: 'work' },
    ],
  },
  {
    id: 'travel',
    title: 'Движение и путешествия',
    description: 'Перемещение, поездки и эксплуатация транспорта',
    verbs: [
      { id: 'set-off', verb: 'Set off', translation: 'отправляться в путь', examples: ['We set off early in the morning.', "Let's set off before sunrise."], category: 'travel' },
      { id: 'take-off-plane', verb: 'Take off (plane)', translation: 'взлетать', examples: ['The plane takes off at 8:00 a.m.', 'My flight takes off in an hour.'], category: 'travel' },
      { id: 'break-down', verb: 'Break down', translation: 'ломаться (о механизмах)', examples: ["Jake's car broke down again.", 'The elevator broke down.'], category: 'travel' },
      { id: 'pull-up', verb: 'Pull up', translation: 'подъезжать, останавливаться', examples: ['The car pulled up at the traffic lights.', 'A taxi pulled up outside.'], category: 'travel' },
      { id: 'get-on-off', verb: 'Get on / Get off', translation: 'садиться / выходить из транспорта', examples: ['Get on the bus.', 'She got on the train at the last minute.', "I'll get off at the next stop."], category: 'travel' },
      { id: 'check-in', verb: 'Check in', translation: 'заселяться в отель, регистрироваться', examples: ['He checked in at the hotel.', 'We need to check in two hours before the flight.'], category: 'travel' },
      { id: 'move-in-out', verb: 'Move in / Move out', translation: 'въезжать / выезжать из жилья', examples: ['When can we move in?', 'We are moving out of the apartment.'], category: 'travel' },
      { id: 'drive-off', verb: 'Drive off', translation: 'уезжать', examples: ['The car drove off.', 'He drove off without saying goodbye.'], category: 'travel' },
      { id: 'run-away', verb: 'Run away', translation: 'убегать, совершать побег', examples: ['The suspect ran away.', 'The dog ran away from home.'], category: 'travel' },
      { id: 'back-up', verb: 'Back up (vehicle)', translation: 'сдавать назад', examples: ['The truck stopped and then backed up.', 'Can you back up a little?'], category: 'travel' },
      { id: 'fall-down', verb: 'Fall down', translation: 'падать', examples: ['The old tree fell down.', "Be careful or you'll fall down."], category: 'travel' },
      { id: 'get-back', verb: 'Get back', translation: 'возвращаться', examples: ["I'll get back home soon.", 'When did you get back from Paris?'], category: 'travel' },
      { id: 'turn-around', verb: 'Turn around', translation: 'развернуться, обернуться', examples: ['She turned around to look at me.', "Turn around, there's a faster route."], category: 'travel' },
      { id: 'get-out', verb: 'Get out', translation: 'выходить', examples: ['Get out of here.', "Let's get out for some fresh air."], category: 'travel' },
      { id: 'drop-off', verb: 'Drop off', translation: 'высаживать из машины', examples: ['Can you drop me off at the station?', "I'll drop you off on my way."], category: 'travel' },
    ],
  },
  {
    id: 'emotions',
    title: 'Эмоции и состояние',
    description: 'Чувства, здоровье, отдых и внутренние реакции',
    verbs: [
      { id: 'give-up', verb: 'Give up', translation: 'сдаваться, бросать', examples: ["You shouldn't give up so easily.", "Don't give up on your goals.", 'Brian gave up smoking last year.'], category: 'emotions' },
      { id: 'calm-down', verb: 'Calm down', translation: 'успокаиваться', examples: ['Take a deep breath and calm down.', 'Calm down, everything will be fine.'], category: 'emotions' },
      { id: 'cheer-up', verb: 'Cheer up', translation: 'взбодриться, развеселиться', examples: ['Cheer up, things will get better.', 'He tried to cheer her up.'], category: 'emotions' },
      { id: 'chill-out', verb: 'Chill out', translation: 'расслабляться, отдыхать', examples: ["Let's chill out and watch a movie.", 'You need to chill out more.'], category: 'emotions' },
      { id: 'look-forward-to', verb: 'Look forward to', translation: 'ждать с нетерпением', examples: ["I'm looking forward to Summer.", "I'm looking forward to the trip.", "I'm looking forward to my vacation."], category: 'emotions' },
      { id: 'zone-out', verb: 'Zone out', translation: 'отключаться, грезить наяву', examples: ['I zoned out during the meeting.', 'She zoned out while reading.'], category: 'emotions' },
      { id: 'come-down-with', verb: 'Come down with', translation: 'заболеть чем-либо', examples: ['Frank came down with the flu.', "I think I'm coming down with a cold."], category: 'emotions' },
      { id: 'pass-out', verb: 'Pass out', translation: 'терять сознание', examples: ['Kevin passed out from the heat.', 'She passed out from exhaustion.'], category: 'emotions' },
      { id: 'work-out-fitness', verb: 'Work out (fitness)', translation: 'тренироваться', examples: ['I work out regularly to keep fit.', 'She works out at the gym every morning.'], category: 'emotions' },
      { id: 'fall-behind', verb: 'Fall behind', translation: 'отставать', examples: ['I fell behind during the hike.', "Don't fall behind with your studies."], category: 'emotions' },
      { id: 'fall-apart', verb: 'Fall apart', translation: 'разваливаться', examples: ["The chair is so old it's starting to fall apart.", 'My plans fell apart.'], category: 'emotions' },
      { id: 'lie-down', verb: 'Lie down', translation: 'прилечь', examples: ["Why don't you lie down and rest?", 'I need to lie down for a minute.'], category: 'emotions' },
      { id: 'hold-on', verb: 'Hold on', translation: 'подождать, держаться', examples: ['Hold on a minute please.', 'Hold on, I forgot my keys.', 'Hold on, you can do this.'], category: 'emotions' },
      { id: 'come-across', verb: 'Come across', translation: 'производить впечатление / случайно найти', examples: ['He comes across as a very confident person.', 'I came across an interesting article.'], category: 'emotions' },
      { id: 'grow-up', verb: 'Grow up', translation: 'расти, взрослеть', examples: ['Kids grow up so fast.', 'Where did you grow up?'], category: 'emotions' },
      { id: 'turn-into', verb: 'Turn into', translation: 'превращаться', examples: ['Caterpillars turn into butterflies.', 'The argument turned into a fight.'], category: 'emotions' },
    ],
  },
  {
    id: 'academic',
    title: 'Учёба и язык',
    description: 'Глаголы для учёбы, исследований и работы с информацией',
    verbs: [
      { id: 'brush-up', verb: 'Brush up (on)', translation: 'освежать знания', examples: ['I need to brush up on my Spanish before the trip.', 'She brushed up on her grammar before the exam.'], category: 'academic' },
      { id: 'carry-on', verb: 'Carry on', translation: 'продолжать', examples: ['Carry on working — you are doing great.', "Don't stop. Carry on with the exercise."], category: 'academic' },
      { id: 'catch-up', verb: 'Catch up', translation: 'догнать, восполнить упущенное', examples: ["I need to catch up with the rest of the group.", 'She studied all weekend to catch up.'], category: 'academic' },
      { id: 'come-through', verb: 'Come through', translation: 'успешно справиться, пройти', examples: ['I came through that exam with a high score.', 'He came through the difficult course.'], category: 'academic' },
      { id: 'come-up-with', verb: 'Come up with', translation: 'придумать, предложить идею', examples: ['She came up with a brilliant idea.', "I can't come up with an answer right now."], category: 'academic' },
      { id: 'fill-in', verb: 'Fill in', translation: 'заполнять пропуски, анкету', examples: ['Fill in the gaps with the correct verb form.', 'Please fill in this registration form.'], category: 'academic' },
      { id: 'flick-through', verb: 'Flick through', translation: 'бегло просматривать', examples: ['I flicked through the textbook before the lecture.', 'She flicked through the article in two minutes.'], category: 'academic' },
      { id: 'jot-down', verb: 'Jot down', translation: 'быстро записать', examples: ["Jot down the key points while I'm talking.", 'I jotted down the new vocabulary words.'], category: 'academic' },
      { id: 'look-into', verb: 'Look into', translation: 'изучать, расследовать', examples: ["I'll look into the matter and get back to you.", 'The teacher looked into the plagiarism case.'], category: 'academic' },
      { id: 'look-through', verb: 'Look through', translation: 'внимательно просматривать', examples: ['Look through your essay before submitting it.', 'I looked through all my notes before the test.'], category: 'academic' },
      { id: 'look-ahead', verb: 'Look ahead / Look back', translation: 'смотреть в будущее / оглядываться в прошлое', examples: ['Look ahead and plan your studies.', 'Looking back, I understand what I did wrong.'], category: 'academic' },
      { id: 'note-down', verb: 'Note down', translation: 'записывать, отмечать', examples: ['Note down the homework assignment.', 'I noted down everything the teacher said.'], category: 'academic' },
      { id: 'stick-to', verb: 'Stick to', translation: 'придерживаться, следовать', examples: ['Stick to the plan and you will succeed.', "I try to stick to my study schedule."], category: 'academic' },
      { id: 'sum-up', verb: 'Sum up', translation: 'подводить итог, резюмировать', examples: ['To sum up, there are three main points.', 'Can you sum up what we learned today?'], category: 'academic' },
      { id: 'log-in-out', verb: 'Log in / Log out', translation: 'входить в систему / выходить', examples: ['Log in with your email and password.', 'Always log out when using a shared computer.'], category: 'academic' },
    ],
  },
  {
    id: 'career',
    title: 'Бизнес и карьера',
    description: 'Профессиональная деятельность, управление и предпринимательство',
    verbs: [
      { id: 'branch-out', verb: 'Branch out', translation: 'расширять сферу деятельности', examples: ['The company branched out into e-commerce.', 'She decided to branch out and try new markets.'], category: 'career' },
      { id: 'bring-about', verb: 'Bring about', translation: 'вызывать, привносить изменения', examples: ['The new CEO brought about significant changes.', 'Technology has brought about a revolution in communication.'], category: 'career' },
      { id: 'bring-forward', verb: 'Bring forward', translation: 'выдвигать, предлагать', examples: ['The team brought forward several proposals.', 'She brought forward a new marketing strategy.'], category: 'career' },
      { id: 'bring-off', verb: 'Bring off', translation: 'успешно справиться с трудным делом', examples: ['It was a difficult negotiation, but she brought it off.', 'The team brought off an amazing project launch.'], category: 'career' },
      { id: 'call-for', verb: 'Call for', translation: 'требовать определённых качеств/навыков', examples: ['This job calls for excellent communication skills.', 'The situation calls for a creative solution.'], category: 'career' },
      { id: 'close-down', verb: 'Close down', translation: 'закрывать (бизнес, компанию)', examples: ['They had to close down the factory.', 'The shop closed down after 30 years.'], category: 'career' },
      { id: 'deal-with', verb: 'Deal with', translation: 'иметь дело с, заниматься', examples: ['I deal with customer complaints every day.', 'She deals with international suppliers.'], category: 'career' },
      { id: 'draw-up', verb: 'Draw up', translation: 'составлять (документ, контракт)', examples: ['The lawyers drew up the contract.', 'Can you draw up a plan for the project?'], category: 'career' },
      { id: 'go-under', verb: 'Go under', translation: 'разориться, потерпеть неудачу (о бизнесе)', examples: ['The company went under during the recession.', 'Three local restaurants went under last year.'], category: 'career' },
      { id: 'lay-off', verb: 'Lay off', translation: 'увольнять сотрудников', examples: ['The company laid off 200 workers.', 'They had to lay off staff due to budget cuts.'], category: 'career' },
      { id: 'measure-up', verb: 'Measure up', translation: 'соответствовать стандартам, требованиям', examples: ["He doesn't measure up to the job requirements.", 'Does the new product measure up to customer expectations?'], category: 'career' },
      { id: 'open-up', verb: 'Open up', translation: 'открывать (новый бизнес)', examples: ['She opened up her own restaurant last year.', "We're planning to open up a new branch."], category: 'career' },
      { id: 'put-forward', verb: 'Put forward', translation: 'выдвигать предложение, идею', examples: ['He put forward an interesting proposal.', 'Several solutions were put forward at the meeting.'], category: 'career' },
      { id: 'sell-out', verb: 'Sell out', translation: 'распродать всё', examples: ['All the tickets sold out in minutes.', 'The product sold out on the first day.'], category: 'career' },
      { id: 'start-up', verb: 'Start up', translation: 'запускать, основывать (бизнес)', examples: ['He started up a software company at 25.', "We're looking for investors to start up the project."], category: 'career' },
      { id: 'take-over', verb: 'Take over', translation: 'захватить, поглотить (компанию)', examples: ['The large corporation took over the small firm.', 'She took over as manager last month.'], category: 'career' },
    ],
  },
  {
    id: 'life-events',
    title: 'Жизнь и отношения',
    description: 'Жизненные ситуации, личные отношения и важные решения',
    verbs: [
      { id: 'ask-out', verb: 'Ask out', translation: 'пригласить на свидание', examples: ['He finally asked her out.', "I'm thinking about asking him out to dinner."], category: 'life-events' },
      { id: 'break-up', verb: 'Break up / Split up', translation: 'расстаться, прекратить отношения', examples: ['They broke up after three years together.', 'She split up with her boyfriend last month.'], category: 'life-events' },
      { id: 'dress-up', verb: 'Dress up / Dress down', translation: 'одеваться официально / неофициально', examples: ['He dressed up for the job interview.', 'It was a casual party, so she dressed down.'], category: 'life-events' },
      { id: 'face-up-to', verb: 'Face up to', translation: 'признать факт, посмотреть в лицо реальности', examples: ['You need to face up to your mistakes.', "It's time to face up to the truth."], category: 'life-events' },
      { id: 'fall-for', verb: 'Fall for', translation: 'влюбиться в кого-либо', examples: ['She fell for him the moment they met.', "I've completely fallen for this city."], category: 'life-events' },
      { id: 'fall-out', verb: 'Fall out', translation: 'поссориться, рассориться', examples: ['They fell out over money.', "I've fallen out with my best friend."], category: 'life-events' },
      { id: 'fall-through', verb: 'Fall through', translation: 'сорваться, не осуществиться (о планах)', examples: ['The deal fell through at the last minute.', 'Our holiday plans fell through.'], category: 'life-events' },
      { id: 'give-in', verb: 'Give in', translation: 'уступить, сдаться под давлением', examples: ["I didn't want to agree, but I gave in.", 'She never gives in when she knows she is right.'], category: 'life-events' },
      { id: 'grow-out-of', verb: 'Grow out of', translation: 'вырасти из (одежды); перерасти (привычку)', examples: ["She's grown out of her shoes already.", 'Most kids grow out of that habit.'], category: 'life-events' },
      { id: 'live-up-to', verb: 'Live up to', translation: 'соответствовать ожиданиям', examples: ['The film didn\'t live up to the hype.', 'She always lives up to her promises.'], category: 'life-events' },
      { id: 'make-out', verb: 'Make out', translation: 'разобрать, понять, уловить', examples: ["I can't make out what the sign says.", 'Can you make out the words in this song?'], category: 'life-events' },
      { id: 'mix-up', verb: 'Mix up', translation: 'перепутать, спутать', examples: ["Don't mix up 'their' and 'there'.", 'I always mix up these two brothers.'], category: 'life-events' },
      { id: 'own-up', verb: 'Own up', translation: 'признаться в содеянном', examples: ['He finally owned up to his mistake.', 'You should own up and apologise.'], category: 'life-events' },
      { id: 'pass-away', verb: 'Pass away', translation: 'скончаться, умереть', examples: ['Her grandmother passed away last winter.', 'He passed away peacefully in his sleep.'], category: 'life-events' },
      { id: 'put-aside', verb: 'Put aside', translation: 'отложить в сторону (сомнения, разногласия)', examples: ['Let\'s put aside our differences and work together.', 'She put her worries aside and focused.'], category: 'life-events' },
      { id: 'see-through', verb: 'See through', translation: 'видеть насквозь, понимать истинную суть', examples: ["I can see through his excuses.", "Don't try to lie — I can see right through you."], category: 'life-events' },
      { id: 'settle-down', verb: 'Settle down', translation: 'успокоиться / обосноваться', examples: ['Settle down, everyone — class is starting.', 'They settled down in the countryside after retirement.'], category: 'life-events' },
      { id: 'stand-up-for', verb: 'Stand up for', translation: 'отстаивать, защищать права', examples: ['Always stand up for what you believe in.', 'She stood up for her colleague in the meeting.'], category: 'life-events' },
      { id: 'stay-up', verb: 'Stay up', translation: 'не ложиться спать, бодрствовать допоздна', examples: ["We stayed up all night talking.", "Don't stay up too late — you have school tomorrow."], category: 'life-events' },
    ],
  },
  {
    id: 'critical',
    title: 'Экстренные ситуации и события',
    description: 'Драматические события, кризисы и ситуации быстрого реагирования',
    verbs: [
      { id: 'beat-up', verb: 'Beat up', translation: 'избивать', examples: ['He was badly beaten up in the attack.', 'They beat him up and stole his wallet.'], category: 'critical' },
      { id: 'black-out', verb: 'Black out', translation: 'потерять сознание, "отключиться"', examples: ['She blacked out from the heat and fell to the floor.', 'He blacked out after the accident.'], category: 'critical' },
      { id: 'blow-up', verb: 'Blow up', translation: 'взорвать / взорваться', examples: ['They blew up the old bridge.', 'The factory blew up because of a gas leak.'], category: 'critical' },
      { id: 'break-in', verb: 'Break in / Break into', translation: 'незаконно вламываться', examples: ['Someone broke into our car last night.', 'Thieves broke in and took all the equipment.'], category: 'critical' },
      { id: 'break-off', verb: 'Break off', translation: 'внезапно прервать (общение, отношения)', examples: ['He broke off all contact with his family.', 'They broke off negotiations without warning.'], category: 'critical' },
      { id: 'break-out', verb: 'Break out', translation: 'внезапно начаться (о войне, пожаре, болезни)', examples: ['A fire broke out in the warehouse.', 'War broke out in the region.'], category: 'critical' },
      { id: 'burn-down', verb: 'Burn down', translation: 'сгореть дотла', examples: ['The old warehouse burned down overnight.', 'The fire burned down three houses.'], category: 'critical' },
      { id: 'burst-into', verb: 'Burst into / Burst out', translation: 'внезапно разразиться (смехом, слезами)', examples: ['She burst into tears when she heard the news.', 'Everyone burst out laughing at his joke.'], category: 'critical' },
      { id: 'cut-off', verb: 'Cut off', translation: 'отключать, прерывать подачу', examples: ['The electricity was cut off due to the storm.', 'They cut off our internet access.'], category: 'critical' },
      { id: 'hack-into', verb: 'Hack into', translation: 'взламывать (компьютер, систему)', examples: ['Hackers broke into the government database.', 'Someone hacked into my email account.'], category: 'critical' },
      { id: 'hold-back', verb: 'Hold back', translation: 'сдерживать (слезы, эмоции, людей)', examples: ["She couldn't hold back her tears.", 'Police held back the crowd.'], category: 'critical' },
      { id: 'hold-up', verb: 'Hold up', translation: 'задерживать / ограбить с оружием', examples: ['We were held up in traffic for two hours.', 'Two men held up the bank.'], category: 'critical' },
      { id: 'hurry-up', verb: 'Hurry up', translation: 'торопиться, ускоряться', examples: ["Hurry up or we'll miss the train!", 'Can you hurry up? We are late.'], category: 'critical' },
      { id: 'knock-down', verb: 'Knock down', translation: 'сбить (человека машиной)', examples: ['A car knocked him down on the crossing.', 'She was knocked down by a cyclist.'], category: 'critical' },
      { id: 'knock-out', verb: 'Knock out', translation: 'отправить в нокаут, вырубить', examples: ['He was knocked out in the third round.', 'The boxer knocked out his opponent.'], category: 'critical' },
      { id: 'run-over', verb: 'Run over', translation: 'переехать, задавить (машиной)', examples: ['A lorry ran over the dog.', 'Be careful — you nearly got run over!'], category: 'critical' },
    ],
  },
  {
    id: 'everyday-talk',
    title: 'Повседневные выражения',
    description: 'Самые употребимые фразовые глаголы в разговорной речи',
    verbs: [
      { id: 'be-back', verb: 'Be back', translation: 'вернуться', examples: ["I'll be back in five minutes.", 'She was back home before midnight.'], category: 'everyday-talk' },
      { id: 'be-over', verb: 'Be over', translation: 'закончиться, завершиться', examples: ['The meeting is over — you can go.', 'Is the film over yet?'], category: 'everyday-talk' },
      { id: 'bear-with', verb: 'Bear with', translation: 'проявить терпение, подождать', examples: ['Bear with me — I just need one more minute.', 'Please bear with us while we fix the issue.'], category: 'everyday-talk' },
      { id: 'come-along', verb: 'Come along', translation: 'идти вместе, присоединиться', examples: ["Come along with us to the market!", 'She came along to the meeting.'], category: 'everyday-talk' },
      { id: 'come-out', verb: 'Come out', translation: 'выходить (о книге, фильме)', examples: ['Her new album comes out next Friday.', 'When does the next Harry Potter come out?'], category: 'everyday-talk' },
      { id: 'come-to', verb: 'Come to', translation: 'прийти к (выводу, заключению)', examples: ["I've come to the conclusion that it's wrong.", 'They came to an agreement at last.'], category: 'everyday-talk' },
      { id: 'come-up-against', verb: 'Come up against', translation: 'столкнуться с (трудностями)', examples: ['We came up against several problems.', 'She came up against a lot of resistance.'], category: 'everyday-talk' },
      { id: 'count-on', verb: 'Count on', translation: 'рассчитывать на кого-либо, полагаться', examples: ['You can always count on me.', 'Can I count on you to help?'], category: 'everyday-talk' },
      { id: 'cut-down', verb: 'Cut down (on)', translation: 'сокращать потребление', examples: ['I need to cut down on sugar.', 'He cut down on smoking to just two a day.'], category: 'everyday-talk' },
      { id: 'die-down', verb: 'Die down', translation: 'затихать, успокаиваться', examples: ['The storm finally died down after midnight.', 'The noise died down when the teacher walked in.'], category: 'everyday-talk' },
      { id: 'dwell-on', verb: 'Dwell on', translation: 'подолгу думать / говорить о чём-то', examples: ["Don't dwell on your mistakes — just move forward.", "I don't want to dwell on the past."], category: 'everyday-talk' },
      { id: 'eat-out', verb: 'Eat out', translation: 'есть вне дома, в кафе или ресторане', examples: ["Let's eat out tonight — I don't want to cook.", 'We eat out every Friday.'], category: 'everyday-talk' },
      { id: 'end-up', verb: 'End up', translation: 'в итоге оказаться, в конечном счёте', examples: ['We got lost and ended up in the wrong city.', 'He studied law but ended up becoming a writer.'], category: 'everyday-talk' },
      { id: 'fed-up-with', verb: 'Fed up with', translation: 'быть сытым по горло, устать от', examples: ["I'm fed up with waiting.", "She's fed up with his excuses."], category: 'everyday-talk' },
      { id: 'get-across', verb: 'Get across', translation: 'донести мысль, объяснить', examples: ['I find it hard to get my point across.', 'Did the teacher get the idea across?'], category: 'everyday-talk' },
      { id: 'get-ahead', verb: 'Get ahead', translation: 'преуспевать, добиться успеха', examples: ['Hard work helps you get ahead in life.', "You need to be creative to get ahead in this field."], category: 'everyday-talk' },
      { id: 'get-at', verb: 'Get at', translation: 'намекать, иметь в виду', examples: ["What are you getting at exactly?", "I'm not sure what she was getting at."], category: 'everyday-talk' },
      { id: 'get-away', verb: 'Get away', translation: 'скрыться, уйти от ответственности', examples: ["The robbers got away in a stolen car.", "Don't let him get away with lying!"], category: 'everyday-talk' },
      { id: 'get-by', verb: 'Get by', translation: 'сводить концы с концами, справляться', examples: ["It's hard to get by on a low salary.", 'We got by on very little money.'], category: 'everyday-talk' },
      { id: 'get-down', verb: 'Get down', translation: 'расстраивать, вгонять в депрессию', examples: ['The bad weather really gets me down.', "Don't let criticism get you down."], category: 'everyday-talk' },
      { id: 'get-down-to', verb: 'Get down to', translation: 'приступать серьёзно к делу', examples: ["Let's get down to business.", "It's time to get down to work."], category: 'everyday-talk' },
      { id: 'get-into', verb: 'Get into', translation: 'попасть в (неприятную) ситуацию', examples: ['How did you get into this mess?', 'He always gets into trouble.'], category: 'everyday-talk' },
      { id: 'get-over', verb: 'Get over', translation: 'оправиться, выздороветь, пережить', examples: ["I hope you get over your cold soon.", "She hasn't got over the breakup yet."], category: 'everyday-talk' },
      { id: 'get-through', verb: 'Get through', translation: 'преодолеть трудности, пройти через', examples: ['We got through a really tough month.', 'I need your help to get through this.'], category: 'everyday-talk' },
      { id: 'get-up', verb: 'Get up', translation: 'вставать (после сна)', examples: ['I get up at 7 every morning.', 'It\'s so hard to get up in winter.'], category: 'everyday-talk' },
      { id: 'give-away', verb: 'Give away', translation: 'отдавать даром, раздавать', examples: ['She gave away all her old clothes.', 'The shop is giving away free samples.'], category: 'everyday-talk' },
      { id: 'give-off', verb: 'Give off', translation: 'издавать, выделять (запах, тепло)', examples: ['The flowers give off a wonderful smell.', 'The engine gives off a lot of heat.'], category: 'everyday-talk' },
      { id: 'go-ahead', verb: 'Go ahead', translation: 'продолжать, начинать, давать разрешение', examples: ["Go ahead — I'm listening.", "Go ahead with the plan."], category: 'everyday-talk' },
      { id: 'go-against', verb: 'Go against', translation: 'идти против (убеждений, правил)', examples: ["It goes against my principles.", "His decision went against the team's wishes."], category: 'everyday-talk' },
      { id: 'go-by', verb: 'Go by', translation: 'проходить (о времени)', examples: ['Time goes by so quickly.', 'Two months went by before we heard from him.'], category: 'everyday-talk' },
      { id: 'go-in-for', verb: 'Go in for', translation: 'заниматься (спортом, хобби)', examples: ['Do you go in for any sports?', 'She goes in for painting in her spare time.'], category: 'everyday-talk' },
      { id: 'go-off', verb: 'Go off', translation: 'испортиться (о еде) / сработать (о будильнике)', examples: ['The milk has gone off.', 'My alarm went off at 6 a.m.'], category: 'everyday-talk' },
      { id: 'go-on', verb: 'Go on', translation: 'продолжать, происходить', examples: ["Go on — don't stop!", "What's going on here?"], category: 'everyday-talk' },
      { id: 'go-out', verb: 'Go out', translation: 'выходить из дома, гулять', examples: ["Let's go out for dinner tonight.", 'She goes out every Friday evening.'], category: 'everyday-talk' },
      { id: 'go-up', verb: 'Go up / Go down', translation: 'расти / снижаться', examples: ['Prices have gone up again.', 'Sales went down last quarter.'], category: 'everyday-talk' },
      { id: 'hang-on-wait', verb: 'Hang on', translation: 'подождать (разговорное)', examples: ['Hang on a second — I need to check.', 'Hang on, let me think about it.'], category: 'everyday-talk' },
      { id: 'hang-up-phone', verb: 'Hang up', translation: 'повесить трубку, завершить звонок', examples: ['She said goodbye and hung up.', "Don't hang up — I have one more question."], category: 'everyday-talk' },
      { id: 'head-for', verb: 'Head for', translation: 'направляться куда-либо', examples: ["We're heading for the airport.", 'After lunch they headed for the beach.'], category: 'everyday-talk' },
      { id: 'help-out', verb: 'Help out', translation: 'выручить, помочь', examples: ['Could you help me out with this task?', 'She often helps out at the local shelter.'], category: 'everyday-talk' },
      { id: 'keep-away', verb: 'Keep away', translation: 'держаться подальше, не приближаться', examples: ['Keep away from that dog — it bites.', 'Keep away from junk food if you want to lose weight.'], category: 'everyday-talk' },
      { id: 'keep-up', verb: 'Keep up', translation: 'не отставать / продолжать в том же духе', examples: ['Keep up the good work!', 'I walk so fast that others can\'t keep up.'], category: 'everyday-talk' },
      { id: 'look-down-on', verb: 'Look down on', translation: 'смотреть свысока, презирать', examples: ["Don't look down on people who earn less.", 'She looked down on anyone who wasn\'t educated.'], category: 'everyday-talk' },
      { id: 'put-out-fire', verb: 'Put out', translation: 'тушить (огонь, пожар)', examples: ['Firefighters put out the blaze in an hour.', 'She put out the candles before leaving.'], category: 'everyday-talk' },
      { id: 'put-through', verb: 'Put through', translation: 'соединять по телефону', examples: ["Hold on — I'll put you through to the manager.", "I'll put you through to customer service."], category: 'everyday-talk' },
      { id: 'put-up', verb: 'Put up', translation: 'повышать (цену) / размещать постояльца', examples: ['The landlord put up the rent again.', "Can you put me up for the night?"], category: 'everyday-talk' },
      { id: 'put-up-with', verb: 'Put up with', translation: 'мириться с, терпеть', examples: ["I can't put up with this noise any longer.", 'She puts up with a lot from her boss.'], category: 'everyday-talk' },
      { id: 'slow-down', verb: 'Slow down', translation: 'замедляться, сбавить скорость', examples: ['Slow down — you are driving too fast!', 'Business has slowed down this winter.'], category: 'everyday-talk' },
      { id: 'take-back', verb: 'Take back', translation: 'возвращать (товар, книги)', examples: ['I need to take these books back to the library.', 'You can take it back to the shop if it doesn\'t fit.'], category: 'everyday-talk' },
      { id: 'take-in', verb: 'Take in (deceive)', translation: 'обмануть, провести', examples: ['I was completely taken in by his story.', "Don't be taken in by those fake reviews."], category: 'everyday-talk' },
      { id: 'talk-over', verb: 'Talk over', translation: 'обсудить проблему', examples: ["Let's talk it over before making a decision.", 'We need to talk over the details.'], category: 'everyday-talk' },
      { id: 'think-over', verb: 'Think over', translation: 'обдумать, поразмыслить', examples: ["I need to think it over before I decide.", 'Think it over and let me know tomorrow.'], category: 'everyday-talk' },
      { id: 'throw-up', verb: 'Throw up', translation: 'тошнить, рвать', examples: ['He felt sick and threw up.', 'The smell made her throw up.'], category: 'everyday-talk' },
      { id: 'try-on', verb: 'Try on', translation: 'примерять (одежду)', examples: ['Can I try this jacket on?', 'She tried on ten dresses before choosing one.'], category: 'everyday-talk' },
      { id: 'wear-out', verb: 'Wear out', translation: 'изнашиваться / измотать, утомить', examples: ['These shoes wore out very quickly.', 'Looking after three kids has completely worn me out.'], category: 'everyday-talk' },
      { id: 'back-up-data', verb: 'Back up (data)', translation: 'сохранять резервную копию данных', examples: ['Back up your files before updating the system.', 'Always back up your work to the cloud.'], category: 'everyday-talk' },
      { id: 'boot-up', verb: 'Boot up', translation: 'загружаться (о компьютере)', examples: ["The computer takes ages to boot up.", 'Boot up the laptop and open the file.'], category: 'everyday-talk' },
      { id: 'buy-up', verb: 'Buy up', translation: 'скупать всё, закупать в большом количестве', examples: ['He bought up all the shares he could find.', 'Fans bought up all the tickets in minutes.'], category: 'everyday-talk' },
      { id: 'brighten-up', verb: 'Brighten up', translation: 'скрасить, сделать лучше, веселее', examples: ['A bunch of flowers brightened up the room.', 'She sent a card to brighten up his day.'], category: 'everyday-talk' },
    ],
  },
]

export function searchPhrasalVerbs(query: string): PhrasalVerb[] {
  const q = query.toLowerCase()
  const results: PhrasalVerb[] = []
  for (const cat of PHRASAL_VERBS_DATA) {
    for (const verb of cat.verbs) {
      if (
        verb.verb.toLowerCase().includes(q) ||
        verb.translation.toLowerCase().includes(q) ||
        verb.examples.some(e => e.toLowerCase().includes(q))
      ) {
        results.push(verb)
      }
    }
  }
  return results
}

export function getAllPhrasalVerbs(): PhrasalVerb[] {
  return PHRASAL_VERBS_DATA.flatMap(c => c.verbs)
}
